language: node_js
node_js:
  - 8.5.0
script:
  - "npm run lint"
  #- "npm run test"

# blocklist
branches:
  except:
  - legacy
  - experimental

# safelist
branches:
  only:
  - master
  - stable

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: jacksonf
  on:
    repo: jacksonfraga/jacksonf-com-br
